name: Build and Deploy

on:
  push:
    paths:
      nginx/index.html

jobs:
  push_to_registry:
    name: Push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo  #hace el pull en el runner para que tenga el codigo y buildear
        uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: cristianvelazquez2021/moni-interview
          tag_with_ref: true  #recarga la imagen con el nombre del brach
          tag_with_sha: true  #para agregar el comentario del commit
          tags: latest, ${{ github.sha }} #comentario corto
       
      
      - name: Deploy to EC2
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}
      - uses: actions/checkout@v2
      - name: run docker-compose
        uses: sudo-bot/action-docker-compose@latest
        with:
        cli-args: "up"
